### ISSUE TITLE
HTTPS fails

### ISSUE THREAD

**Issue by q60** [ducdetronquito/http#23]
don't want to make a mess in an issue, so i made a gist:

https://gist.github.com/q60/4d875206006df803d8f7c7daf5acb997

**Comment by ducdetronquito** [comment]
Thanks !
I am at work right now so I cannot look into it, but I will do tonight :)

**Comment by q60** [comment]
Zig 0.9.0 running linux x86_64

**Comment by ducdetronquito** [comment]
I moved this issue to requestz's repository: https://github.com/ducdetronquito/requestz/issues/22
